### ISSUE TITLE
Good-to-have Features Tracking

### ISSUE THREAD

**Issue by R4356th** [snapwiki/snapwiki.github.io#9]
Here are some features we need to discuss about and track-
* [x] Service Worker - #8 (More like a must-have feature, now that we have a manifest and want it to be a PWA)
* [x] security.txt - Done by @GrahamSH-LLK and @R4356th 
* [x] robots.txt - Done by @GrahamSH-LLK
* [x] Sitemap - Done by @GrahamSH-LLK
* [x] API for status page so that Snap<i>!</i> Wiki Discord bot can make requests to it and reply with the response - Done by @R4356th and @GrahamSH-LLK
* [x] Page about SnapProjectEmbed extension - In progress
* [x] Testing the website's PWA features on multiple browsers and operating systems
   * [x] ChromeOS (Chrome)
   * [x] Windows 
        * [x] Chrome
        * [x] Edge
   * [x] Linux (Chrome)
   * [x] iOS (Safari [has bad support in general])
   * [x] Android (Chrome)
   * [x] MacOS

**Comment by GrahamSH-LLK** [comment]
PWA's looking good! 
![Screenshot 2020-11-05 at 7 59 29 AM](https://user-images.githubusercontent.com/64214252/98244128-ee36ce00-1f3c-11eb-99ef-4ab3c913d834.png)

**Comment by GrahamSH-LLK** [comment]
I made it so that the top strip matches the theme.

**Comment by R4356th** [comment]
> I made it so that the top strip matches the theme.

What top strip?

**Comment by GrahamSH-LLK** [comment]
![image](https://user-images.githubusercontent.com/64214252/98261404-6cea3600-1f52-11eb-9af2-4f73cb82b34c.png)

**Comment by R4356th** [comment]
This got resolved a long time ago. Nobody just bothered to close this!
